/*
 * Company: HexeFX
 * Effect Name: Plate Reverb
 * Description: A lush sounding plate reverb. Open-source @ github.com/hexeguitar/t40fx.
 *
 * This file was auto-generated by Stride Audio Effect Creator for the STRIDE.
 */
#include <cmath>
#include "Stride/LibBasicFunctions.h"
#include "PlateReverb.h"

using namespace Stride;

namespace HexeFX_PlateReverb {

void PlateReverb::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void PlateReverb::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : reverb( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : tone( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 3 : wetmix( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 4 : echo( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 5 : lowcut( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 6 : highcut( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 7 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 8 : outputmode( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float PlateReverb::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // reverb
    case 2 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // tone
    case 3 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // wetmix
    case 4 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // echo
    case 5 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // lowcut
    case 6 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // highcut
    case 7 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 8 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // outputmode
    default : return 0.0f;
    }
}

void PlateReverb::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Reverb_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Reverb_e][MIDI_CONTROL] == control)) {
        reverb(val);
        return;
    }

    if ((m_midiConfig[Tone_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Tone_e][MIDI_CONTROL] == control)) {
        tone(val);
        return;
    }

    if ((m_midiConfig[WetMix_e][MIDI_CHANNEL] == channel) && (m_midiConfig[WetMix_e][MIDI_CONTROL] == control)) {
        wetmix(val);
        return;
    }

    if ((m_midiConfig[Echo_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Echo_e][MIDI_CONTROL] == control)) {
        echo(val);
        return;
    }

    if ((m_midiConfig[LowCut_e][MIDI_CHANNEL] == channel) && (m_midiConfig[LowCut_e][MIDI_CONTROL] == control)) {
        lowcut(val);
        return;
    }

    if ((m_midiConfig[HighCut_e][MIDI_CHANNEL] == channel) && (m_midiConfig[HighCut_e][MIDI_CONTROL] == control)) {
        highcut(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[OutputMode_e][MIDI_CHANNEL] == channel) && (m_midiConfig[OutputMode_e][MIDI_CONTROL] == control)) {
        outputmode(val);
        return;
    }

}

audio_block_t* PlateReverb::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = {};
const uint8_t* PlateReverb::getRblk() { return rblk; }
static constexpr char PROGMEM PlateReverb_name[] = {0x48, 0x65, 0x78, 0x65, 0x46, 0x58, 0x3a, 0x44, 0x3a, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x20, 0x52, 0x65, 0x76, 0x65, 0x72, 0x62, 0x0};
const char* PlateReverb::getName() { return PlateReverb_name; }

}
